"""
AgentMail integration for sending email drafts to BDR.
Uses the official AgentMail Python SDK.
"""
import os
import requests
from agentmail import AgentMail


_cached_inbox = None


def get_agentmail_credentials():
    """Get AgentMail credentials from Replit connector."""
    hostname = os.environ.get('REPLIT_CONNECTORS_HOSTNAME')
    
    repl_identity = os.environ.get('REPL_IDENTITY')
    web_repl_renewal = os.environ.get('WEB_REPL_RENEWAL')
    
    if repl_identity:
        x_replit_token = f'repl {repl_identity}'
    elif web_repl_renewal:
        x_replit_token = f'depl {web_repl_renewal}'
    else:
        return None
    
    if not hostname:
        return None
    
    try:
        response = requests.get(
            f'https://{hostname}/api/v2/connection?include_secrets=true&connector_names=agentmail',
            headers={
                'Accept': 'application/json',
                'X_REPLIT_TOKEN': x_replit_token
            },
            timeout=10
        )
        
        if response.status_code == 200:
            data = response.json()
            items = data.get('items', [])
            if items and items[0].get('settings', {}).get('api_key'):
                return {
                    'api_key': items[0]['settings']['api_key']
                }
    except Exception as e:
        print(f"[AGENTMAIL] Failed to get credentials: {e}")
    
    return None


def get_agentmail_client():
    """Get an AgentMail client instance."""
    creds = get_agentmail_credentials()
    if not creds or not creds.get('api_key'):
        return None
    
    return AgentMail(api_key=creds['api_key'])


def is_agentmail_configured():
    """Check if AgentMail is configured."""
    creds = get_agentmail_credentials()
    return creds is not None and creds.get('api_key')


def get_or_create_inbox():
    """Get existing inbox or create a new one using the SDK."""
    global _cached_inbox
    
    if _cached_inbox:
        return _cached_inbox
    
    client = get_agentmail_client()
    if not client:
        print("[AGENTMAIL] No client available")
        return None
    
    try:
        response = client.inboxes.list()
        if response.inboxes:
            _cached_inbox = response.inboxes[0]
            print(f"[AGENTMAIL] Using existing inbox: {_cached_inbox.inbox_id}")
            return _cached_inbox
        
        _cached_inbox = client.inboxes.create()
        print(f"[AGENTMAIL] Created new inbox: {_cached_inbox.inbox_id}")
        return _cached_inbox
        
    except Exception as e:
        print(f"[AGENTMAIL] Failed to get/create inbox: {e}")
        return None


def send_email_draft(to_email: str, subject: str, body: str, company_name: str = None, report_url: str = None):
    """
    Send an email draft to the BDR.
    
    Args:
        to_email: BDR email address
        subject: Email subject line
        body: Email body text
        company_name: Company name for context
        report_url: URL to the full report
    
    Returns:
        dict with success status and message
    """
    client = get_agentmail_client()
    if not client:
        return {'success': False, 'error': 'AgentMail not configured'}
    
    inbox = get_or_create_inbox()
    if not inbox:
        return {'success': False, 'error': 'Failed to get/create inbox'}
    
    inbox_id = inbox.inbox_id
    
    if not inbox_id:
        return {'success': False, 'error': 'Invalid inbox configuration'}
    
    email_body = f"""New Lead Alert: {company_name or 'Unknown Company'}

--- READY-TO-SEND COLD EMAIL ---

SUBJECT: {subject}

BODY:
{body}

---

{f'View full report: {report_url}' if report_url else ''}

This email was generated by Lead Machine based on detected localization signals.
"""
    
    try:
        client.inboxes.messages.send(
            inbox_id=inbox_id,
            to=[to_email],
            subject=f'[Lead Alert] {company_name or "New Lead"} - Cold Email Draft Ready',
            text=email_body
        )
        
        print(f"[AGENTMAIL] Email sent to {to_email}")
        return {'success': True, 'message': f'Email sent to {to_email}'}
        
    except Exception as e:
        print(f"[AGENTMAIL] Send failed: {e}")
        return {'success': False, 'error': str(e)}
