"""
AgentMail integration for sending email drafts to BDR.
"""
import os
import requests


def get_agentmail_credentials():
    """Get AgentMail credentials from Replit connector."""
    hostname = os.environ.get('REPLIT_CONNECTORS_HOSTNAME')
    
    repl_identity = os.environ.get('REPL_IDENTITY')
    web_repl_renewal = os.environ.get('WEB_REPL_RENEWAL')
    
    if repl_identity:
        x_replit_token = f'repl {repl_identity}'
    elif web_repl_renewal:
        x_replit_token = f'depl {web_repl_renewal}'
    else:
        return None
    
    if not hostname:
        return None
    
    try:
        response = requests.get(
            f'https://{hostname}/api/v2/connection?include_secrets=true&connector_names=agentmail',
            headers={
                'Accept': 'application/json',
                'X_REPLIT_TOKEN': x_replit_token
            },
            timeout=10
        )
        
        if response.status_code == 200:
            data = response.json()
            items = data.get('items', [])
            if items and items[0].get('settings', {}).get('api_key'):
                return {
                    'api_key': items[0]['settings']['api_key']
                }
    except Exception as e:
        print(f"[AGENTMAIL] Failed to get credentials: {e}")
    
    return None


def is_agentmail_configured():
    """Check if AgentMail is configured."""
    creds = get_agentmail_credentials()
    return creds is not None and creds.get('api_key')


def create_inbox():
    """Create a new inbox for sending emails."""
    creds = get_agentmail_credentials()
    if not creds:
        return None
    
    try:
        response = requests.post(
            'https://api.agentmail.to/v1/inboxes',
            headers={
                'Authorization': f'Bearer {creds["api_key"]}',
                'Content-Type': 'application/json'
            },
            json={},
            timeout=10
        )
        
        if response.status_code in (200, 201):
            return response.json()
    except Exception as e:
        print(f"[AGENTMAIL] Failed to create inbox: {e}")
    
    return None


def list_inboxes():
    """List existing inboxes."""
    creds = get_agentmail_credentials()
    if not creds:
        return []
    
    try:
        response = requests.get(
            'https://api.agentmail.to/v1/inboxes',
            headers={
                'Authorization': f'Bearer {creds["api_key"]}',
                'Content-Type': 'application/json'
            },
            timeout=10
        )
        
        if response.status_code == 200:
            return response.json().get('inboxes', [])
    except Exception as e:
        print(f"[AGENTMAIL] Failed to list inboxes: {e}")
    
    return []


def get_or_create_inbox():
    """Get existing inbox or create a new one."""
    inboxes = list_inboxes()
    if inboxes:
        return inboxes[0]
    return create_inbox()


def send_email_draft(to_email: str, subject: str, body: str, company_name: str = None, report_url: str = None):
    """
    Send an email draft to the BDR.
    
    Args:
        to_email: BDR email address
        subject: Email subject line
        body: Email body text
        company_name: Company name for context
        report_url: URL to the full report
    
    Returns:
        dict with success status and message
    """
    creds = get_agentmail_credentials()
    if not creds:
        return {'success': False, 'error': 'AgentMail not configured'}
    
    inbox = get_or_create_inbox()
    if not inbox:
        return {'success': False, 'error': 'Failed to get/create inbox'}
    
    inbox_id = inbox.get('id')
    from_email = inbox.get('email')
    
    if not inbox_id or not from_email:
        return {'success': False, 'error': 'Invalid inbox configuration'}
    
    email_body = f"""New Lead Alert: {company_name or 'Unknown Company'}

--- READY-TO-SEND COLD EMAIL ---

SUBJECT: {subject}

BODY:
{body}

---

{f'View full report: {report_url}' if report_url else ''}

This email was generated by Lead Machine based on detected localization signals.
"""
    
    try:
        response = requests.post(
            f'https://api.agentmail.to/v1/inboxes/{inbox_id}/messages',
            headers={
                'Authorization': f'Bearer {creds["api_key"]}',
                'Content-Type': 'application/json'
            },
            json={
                'to': [{'email': to_email}],
                'from': {'email': from_email, 'name': 'Lead Machine'},
                'subject': f'[Lead Alert] {company_name or "New Lead"} - Cold Email Draft Ready',
                'text': email_body
            },
            timeout=15
        )
        
        if response.status_code in (200, 201, 202):
            return {'success': True, 'message': f'Email sent to {to_email}'}
        else:
            return {'success': False, 'error': f'API error: {response.status_code}'}
    except Exception as e:
        return {'success': False, 'error': str(e)}
