"""
PDF Generation Module for Lead Machine Reports.
Uses fpdf2 to create professional sales intelligence reports.
"""
from fpdf import FPDF
from datetime import datetime
import os

class ReportPDF(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('helvetica', 'B', 15)
        self.set_text_color(26, 35, 126) # Dark Blue
        self.cell(0, 10, 'Lead Machine - Sales Intelligence Report', ln=True, align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Lead Machine on {datetime.now().strftime("%Y-%m-%d")}', align='C')

def generate_report_pdf(report, output_path):
    """
    Generate a professional PDF report from a database report object.
    """
    pdf = ReportPDF()
    pdf.add_page()

    # Ensure scan_data is a dict (may be None or empty from database)
    scan_data = report.get('scan_data') or {}

    # 1. Company Info Header
    pdf.set_font('helvetica', 'B', 24)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, report['company_name'], ln=True)

    pdf.set_font('helvetica', '', 12)
    pdf.set_text_color(0, 100, 255)
    pdf.cell(0, 8, f"github.com/{report['github_org']}", ln=True, link=scan_data.get('org_url', ''))
    
    pdf.ln(5)
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"Scanned on: {report['created_at']}", ln=True)
    pdf.ln(10)

    # 2. Executive Summary
    ai = report.get('ai_analysis', {})
    if ai.get('executive_summary'):
        pdf.set_fill_color(240, 248, 255)
        pdf.set_font('helvetica', 'B', 14)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 10, ' Executive Summary', ln=True, fill=True)
        pdf.ln(3)
        pdf.set_font('helvetica', '', 11)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 6, ai['executive_summary'])
        pdf.ln(10)

    # 3. Assessment Stats
    pdf.set_font('helvetica', 'B', 14)
    pdf.set_text_color(26, 35, 126)
    pdf.cell(0, 10, ' Strategic Assessment', ln=True)
    pdf.ln(3)
    
    # Grid of stats
    pdf.set_font('helvetica', 'B', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(45, 10, 'Maturity Level:', ln=False)
    
    maturity = ai.get('localization_maturity', 'Unknown').upper()
    pdf.set_font('helvetica', 'B', 10)
    if 'ADVANCED' in maturity: pdf.set_text_color(91, 33, 182)
    elif 'MATURE' in maturity: pdf.set_text_color(5, 150, 105)
    elif 'DEVELOPING' in maturity: pdf.set_text_color(30, 64, 175)
    else: pdf.set_text_color(146, 64, 14)
    
    pdf.cell(45, 10, maturity, ln=True)
    
    pdf.set_font('helvetica', 'B', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(45, 10, 'Opportunity Score:', ln=False)
    score = ai.get('opportunity_score', 0)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(45, 10, f"{score}/10", ln=True)
    
    # Semantic Analysis section
    if ai.get('semantic_analysis'):
        sem = ai['semantic_analysis']
        pdf.ln(5)
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 8, ' Semantic Intelligence:', ln=True)
        # Severity Badge-like text
        pdf.set_font('helvetica', 'B', 9)
        sev = sem.get('severity', 'minor').upper()
        if sev == 'CRITICAL': pdf.set_text_color(220, 38, 38)
        elif sev == 'MAJOR': pdf.set_text_color(234, 88, 12)
        else: pdf.set_text_color(217, 119, 6)
        pdf.cell(0, 7, f" Severity: {sev} | Category: {sem.get('primary_pain_category', 'N/A').replace('_', ' ').title()}", ln=True)
        pdf.set_font('helvetica', 'I', 10)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 6, f'"{sem.get("description", "")}"')

    # Compliance Risk section
    if ai.get('compliance_risk'):
        comp = ai['compliance_risk']
        pdf.ln(5)
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 8, ' Compliance Risk Assessment:', ln=True)
        pdf.set_font('helvetica', 'B', 9)
        risk_lvl = comp.get('level', 'low').upper()
        if risk_lvl == 'CRITICAL' or risk_lvl == 'HIGH': pdf.set_text_color(220, 38, 38)
        else: pdf.set_text_color(22, 163, 74)
        pdf.cell(0, 7, f" Risk Level: {risk_lvl}", ln=True)
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 6, comp.get('description', ''))

    # Forensic Evidence section
    if ai.get('forensic_evidence'):
        pdf.ln(5)
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 8, ' External Forensic Evidence:', ln=True)
        pdf.set_font('helvetica', 'I', 10)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 6, ai['forensic_evidence'])
    
    pdf.ln(5)

    # 4. Tech Stack & Pain Points (High Intent)
    if ai.get('pain_point_analysis'):
        pdf.set_font('helvetica', 'B', 14)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 10, ' Pain Point Analysis', ln=True)
        pdf.ln(2)
        pdf.set_font('helvetica', '', 11)
        pdf.set_text_color(220, 38, 38) # Red for pain
        pdf.multi_cell(0, 6, ai['pain_point_analysis'])
        pdf.ln(8)

    # 5. Top Prospects (New Section)
    if ai.get('top_prospects'):
        pdf.set_font('helvetica', 'B', 14)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 10, ' High-Value Outreach Prospects', ln=True)
        pdf.ln(3)
        for prospect in ai['top_prospects']:
            pdf.set_font('helvetica', 'B', 11)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 7, f"{prospect.get('name')} (@{prospect.get('login')})", ln=True)
            pdf.set_font('helvetica', 'B', 10)
            pdf.set_text_color(0, 102, 204)
            pdf.cell(0, 6, f" Role: {prospect.get('role_inference')}", ln=True)
            
            pdf.set_font('helvetica', '', 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 5, f" Strategy: {prospect.get('outreach_strategy')}")
            pdf.set_font('helvetica', 'I', 10)
            pdf.set_text_color(100, 100, 100)
            pdf.multi_cell(0, 5, f" Icebreaker: {prospect.get('icebreaker')}")
            pdf.ln(4)
        pdf.ln(5)

    if ai.get('tech_stack_hook'):
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 8, ' Technical Integration Hook', ln=True)
        pdf.set_font('helvetica', 'I', 11)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 6, ai['tech_stack_hook'])
        pdf.ln(8)

    # 5. Key Findings
    if ai.get('key_findings'):
        pdf.set_font('helvetica', 'B', 14)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 10, ' Key Intelligence Findings', ln=True)
        pdf.ln(2)
        for finding in ai['key_findings']:
            pdf.set_font('helvetica', 'B', 11)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(8, 6, '-', ln=False)
            pdf.multi_cell(0, 6, finding['finding'])
            pdf.set_font('helvetica', 'I', 9)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(8)
            pdf.multi_cell(0, 5, f"Sales Angle: {finding.get('sales_angle', finding.get('evidence', ''))}")
            pdf.ln(2)
        pdf.ln(5)

    # 5b. Outreach Suggestions
    if ai.get('outreach_suggestions'):
        pdf.set_font('helvetica', 'B', 14)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 10, ' Outreach Suggestions', ln=True)
        pdf.ln(2)
        for index, suggestion in enumerate(ai['outreach_suggestions'][:10], start=1):
            pdf.set_font('helvetica', 'B', 11)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 6, f"{index}. Why this account", ln=True)
            pdf.set_font('helvetica', '', 10)
            pdf.multi_cell(0, 5, suggestion.get('why_account', ''))

            pdf.set_font('helvetica', 'B', 10)
            pdf.cell(0, 5, "Why now", ln=True)
            pdf.set_font('helvetica', '', 10)
            pdf.multi_cell(0, 5, suggestion.get('why_now', ''))

            pdf.set_font('helvetica', 'B', 10)
            pdf.cell(0, 5, "Who to reach", ln=True)
            pdf.set_font('helvetica', '', 10)
            pdf.multi_cell(0, 5, suggestion.get('who_to_reach', ''))

            pdf.set_font('helvetica', 'B', 10)
            pdf.cell(0, 5, "Message hook", ln=True)
            pdf.set_font('helvetica', '', 10)
            pdf.multi_cell(0, 5, suggestion.get('message_hook', ''))
            pdf.ln(2)
        pdf.ln(5)

    # 6. Email Draft (New Page if needed)
    if ai.get('email_draft'):
        pdf.add_page()
        pdf.set_font('helvetica', 'B', 16)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 12, ' Personalization Draft (Email)', ln=True)
        pdf.ln(5)
        
        draft = ai['email_draft']
        pdf.set_fill_color(245, 245, 245)
        pdf.set_font('helvetica', 'B', 11)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 10, f" Subject: {draft.get('subject', '')}", ln=True, fill=True)
        pdf.ln(3)
        
        pdf.set_font('helvetica', '', 11)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 7, draft.get('body', ''))
        pdf.ln(10)

    # 7. Next Steps
    if ai.get('next_steps'):
        pdf.set_font('helvetica', 'B', 14)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 10, ' Recommended Next Steps', ln=True)
        pdf.ln(3)
        for step in ai['next_steps']:
            pdf.set_font('helvetica', '', 11)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(15, 8, ' [ ] ', ln=False)
            pdf.cell(0, 8, step, ln=True)
        pdf.ln(10)

    # 8. Signals (Top 10)
    signals = scan_data.get('signals', [])
    if signals:
        pdf.set_font('helvetica', 'B', 14)
        pdf.set_text_color(26, 35, 126)
        pdf.cell(0, 10, f' Recent Signals Detected ({len(signals)})', ln=True)
        pdf.ln(3)
        
        pdf.set_font('helvetica', 'B', 9)
        pdf.set_fill_color(230, 230, 230)
        pdf.cell(35, 8, ' Type', border=1, fill=True)
        pdf.cell(140, 8, ' Content/File', border=1, fill=True, ln=True)
        
        pdf.set_font('helvetica', '', 8)
        for sig in signals[:15]: # Show top 15
            sig_type = sig.get('type', 'Unknown').replace('_', ' ').title()
            content = ""
            if sig.get('type') == 'commit_message': content = sig.get('message', '')
            elif sig.get('type') == 'pull_request': content = f"PR #{sig.get('number')}: {sig.get('title')}"
            elif sig.get('type') == 'file_change': content = sig.get('file', '')
            elif sig.get('type') == 'frustration_signal': content = f"{sig.get('message', '')}"
            
            # Truncate content for PDF table
            if len(content) > 85: content = content[:82] + "..."

            pdf.cell(35, 7, f" {sig_type}", border=1)
            pdf.cell(140, 7, f" {content}", border=1, ln=True)

    pdf.output(output_path)
    return output_path
